env:
  node              : true
  browser           : true
  es2021            : true

extends:
  - standard-with-typescript

overrides           : []

parserOptions:
  ecmaVersion       : latest
  sourceType        : module
  project:
   - tsconfig.json

rules:
  semi              : [ 2, never ]
  one-var           : off
  return-await      : off
  indent            : off
  no-multi-spaces   : off
  array-bracket-spacing:
    - error
    - always
  key-spacing:
    - error
    - multiLine:
        beforeColon : false
        afterColon  : true
      align:
        beforeColon : true
        afterColon  : true

  "@typescript-eslint/indent": off
  "@typescript-eslint/return-await": [ 1, "in-try-catch" ]
  "@typescript-eslint/no-base-to-string": off
  "@typescript-eslint/type-annotation-spacing":
    - error
    - before        : true
      after         : true
      overrides:
        arrow:
          before    : true
          after     : true

ignorePatterns:
  - build
  - coverage
  - dist
  - test
  - rollup.config.ts
